# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "https://github.com/Shinyhunter2109/Discord-Moveset-Bot/wiki"
    directory: "https://github.com/Shinyhunter2109/Discord-Moveset-Bot/blob/master/Getting%20Started/Updater%20for%20Dependencies/Windows%2010/Updater.bat/"
    schedule:
      interval: "weekly"

